# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 22:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0045_auto_20170217_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(default='DummyId', max_length=60, unique=True, validators=[django.core.validators.RegexValidator(regex=b'^[-_:a-zA-Z0-9]+$')], verbose_name=b'Sensor ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
